### ISSUE TITLE
can't run, no service available (on DC)

### ISSUE THREAD

**Issue by facgure** [QuantumObject/docker-dspace#14]
Hi & thank to maintainer,

I installed on ubuntu at DigitalOcean and got `docker ps` below:
```
CONTAINER ID        IMAGE                                COMMAND             CREATED              STATUS              PORTS                    NAMES
6ede72d405b1        quantumobject/docker-dspace:latest   "/sbin/my_init"     About a minute ago   Up About a minute   0.0.0.0:8080->8080/tcp   stupefied_curie

```
I cannot preview for `http://<myip>:8080/jspui/` or `.../xmlui/`. I am a newbie for docker & dspace. Please suggest me more information, how to check my dspace service on the machine.

Thx a lot.

**Comment by angelrr7702** [comment]
did you run this command ?

 docker exec -it 6ede72d405b1  create-admin

This is to create admin account with password. if that fail let me know the msg error and distribution  of Linux, and version of docker you are using . 

sincerely
Angel Rodriguez

**Comment by angelrr7702** [comment]
reopen if still have the same problem...
