### ISSUE TITLE
Update for DSpace v.6.0?

### ISSUE THREAD

**Issue by xicubed** [QuantumObject/docker-dspace#17]
I'm trying to do this but running into some problems. I made my own docker-tomcat8 and reference FROM quantumobject/docker-baseimage:16.04 instead of 15.10... but still running into errors.

**Comment by angelrr7702** [comment]
ok, I will try to update today . thanks to let me know ... if you send any copy of your error and any change need to be done . that will help me .

**Comment by xicubed** [comment]
Docker/Ubuntu 16.04's postgres is 9.5. Seems like postgress wont start then the rest of the dSpace install fails too...
Get an error something like:
	     ```Is the server running locally and accepting
	     connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?```

**Comment by angelrr7702** [comment]
ok, thanks I will update when done .

**Comment by angelrr7702** [comment]
Done. update to version 6.0 .

I have to change to make it work : 

-- install ubuntu package postgresql-contrib  that include "pgcrypto" that is required for version 6.0
    
-- remove some line relate to ssl for postgress and disable it .
       sed -i 's/ssl = true/ssl = false/' /etc/postgresql/9.4/main/postgresql.conf
--  add extension "pgcrypto" to database dspace : 
        chpst -u postgres psql dspace <<< "CREATE EXTENSION pgcrypto;" &>/dev/null

please let me know if it working correctly . or any other recommendation for it .

sincerely
Angel Rodriguez

**Comment by xicubed** [comment]
Great thanks, I just installed and it's working. I did get one warning but still seems to be working...

```
$ docker exec -it dspace create-admin
ok: down: tomcat8: 0s, normally up

WARNING: 'clean' command is currently disabled, as it is dangerous to run in Production scenarios!

In order to run a 'clean' you first must enable it in your DSpace config by specifying 'db.cleanDisabled=false'.

Creating an initial administrator account
```

**Comment by angelrr7702** [comment]
Hi,
 yes. before  I used the clean command by reference of wiki relate to the install.  I was able to add email and password and web page worked for me .. I didn't have time to check if working perfect and correctly .

did this warning affect deployment ? and did everything else was working fine ?

sincerely
Angel Rodriguez
