### ISSUE TITLE
problem with access to the certificate postgres

### ISSUE THREAD

**Issue by ASudri** [QuantumObject/docker-dspace#2]
Thank You for your container.
After running the script "docker exec -it container_id /bin/bash /dspace/bin/dspace create-administrator" I get the error in  /var/log/postgresd.log  "FATAL: could not access private key file "/etc/ssl/private/ssl-cert-snakeoil.key": Permission denied" 

Found a description and workaround here https://github.com/docker/docker/issues/783
I realized this mistake AUFS, perhaps it makes sense to add a description of the solution

**Comment by bram-atmire** [comment]
FYI, I tried to deploy using tutum and still ran against this same problem

**Comment by angelrr7702** [comment]
Maybe we can try to separate  postgres from this container ... running the official postgres database docker container and then link with this container after removing the database from it .   I will test later if that will work . I have already remove  from some of my container the mysql database , the only difference is that you need to execute two container .. for the application to work .. database container and the linked application container .

**Comment by bram-atmire** [comment]
Seems like bumping the postgres version would also solve it:
https://wiki.postgresql.org/wiki/May_2015_Fsync_Permissions_Bug

**Comment by angelrr7702** [comment]
Thanks for the link .. I add the fix that show that link plus a remove 3rd party repository for postgresql for the official ubuntu repository(already update to 9.4) .. please try it again and let me know if problem still show.
