### ISSUE TITLE
dspace create-administrator fails

### ISSUE THREAD

**Issue by ezmac** [QuantumObject/docker-dspace#3]
docker exec -it container_id /bin/bash /dspace/bin/dspace create-administrator fails.

Postgres is not running because /etc/ssl/private/ssl-cert-snakeoil.key is not readable by postgres user.  By moving the file to /etc/ssl/postgres/ and changing the config file, I was able to start postgres and get this container to work properly.

**Comment by angelrr7702** [comment]
I will check what I can do to fix it ... it is maybe relate to pre error that I can't reproduce on my system . relate to AUFS problem ... and docker . please check closed issue ..

**Comment by ezmac** [comment]
Sorry for the duplicate issue.  I completely missed the closed one.  I've worked the fix into the pre-conf.sh script and gotten it working with the instructions in the readme.  Postgres has updated to 9.4, which changed some other files.  Would you like a pull request for it?

Otherwise, closing it is fine by me.

**Comment by angelrr7702** [comment]
yes, please with the pull request for the change done at pre-conf.sh done by you to fix the problem .. I appreciate it ..

sincerely
Angel Rodriguez
